### PR TITLE
filter out nans before taking max

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by pkofod** [comment]
is it prettier now?

**Comment by mkborregaard** [comment]
In Plots we use the NaNMath functions, but there are so few cases of `maximum`, `extrema` etc in PlotUtils that it may not be worth striving for consistency.

**Comment by mkborregaard** [comment]
Wonderfully simple fix too :-)

**Comment by KristofferC** [comment]
Pretty as a button... 

image

image

**Pull request merged**
