### PR TITLE
uncomment colorbrewer's categorical themes

### PR DESCRIPTION
**Pull request by daschw**
This was actually @mkborregaard 's work, I'm just uncommenting the code.
The cagetorical gradients/palettes can be used in Plots with, e.g.
```
plot(rand(10, 6), palette = :Dark2)
```

### CODE REVIEW

**Comment by mkborregaard** [comment]
Thanks :-D :heart: I'd completely forgotten that they actually were in there somewhere.
Do you think we should have some mention of this in the color docs too?

**Comment by daschw** [comment]
I guess more information in the docs is always nice to have.

**Comment by mkborregaard** [comment]
I think the reason I left them commented was because I didn't feel we had a good enough system for letting people know that these were not color gradients, they were palettes. With this PR, I guess they will show up as gradients in `showlibrary()` no? Maybe an easy solution would be to just put them in their own library called "categorical", though that is not really a clean solution.

**Comment by daschw** [comment]
> With this PR, I guess they will show up as gradients in showlibrary() no?

Yes.
Colorbrewer also does not really distinguish between them other than calling them sequential, diverging and qualitative, no?
A sequential gradient can also be used as palette in Plots and a qualitative/categorical palette could be used as gradient (technically). I mean, technically in PlotUtils there is no difference. I think it's fine to add something about that in th Docs color section, but would keep the categorical colors from colorbrewer in the library. I haven't given this much thought though.

**Comment by mkborregaard** [comment]
I guess that works too. Sometimes it makes sense not to overcomplicate things :-)

**Pull request merged**
