### PR TITLE
Add Dates as a dependency in Julia v0.7

### LINKED ISSUE #36: Add support for Julia v0.7
This one is not compiling due to `Date` not being defined.

### PR DESCRIPTION
**Pull request by juliohm**
Fix #36

### CODE REVIEW

**Comment by mkborregaard** [comment]
Great, thanks! Is this safe to merge now or should it wait for 0.7?

**Comment by juliohm** [comment]
I am not sure @mkborregaard , but I could install the `Dates` package on Julia v0.6 as well. Maybe the changes are safe to merge? I am fine with what I have locally. I am currently in the phase of porting my packages to Julia v0.7, or at least try to estimate how much needs to be done.

**Comment by mkborregaard** [comment]
I've created a julia0.7 branch here too - if you'll redirect the PR to there, I'll merge :-)

**Comment by juliohm** [comment]
Closing in favor of #38

**Pull request closed without merging**
