### PR TITLE
Various ticks fixes (precision, log scale)

### PR DESCRIPTION
**Pull request by t-bltg**
1. Fix precision issues (fix https://github.com/JuliaPlots/PlotUtils.jl/issues/114);
2. Relax exponent integer constraint when computing log based ticks (fix https://github.com/JuliaPlots/PlotUtils.jl/issues/116, fix  https://github.com/JuliaPlots/Plots.jl/issues/3918).
3. Coding style.
4. Update CI script, using julia LTS `1.6` and latest `1.7` (following https://github.com/JuliaPlots/Plots.jl/pull/3966).
5. Drop julia versions < `1.6` for consistency with `Plots`.
6. Bump minor version.
7. Add formatting github action, as in `Plots`.

Xref: https://github.com/JuliaPlots/Plots.jl/issues/3790, https://github.com/JuliaPlots/Plots.jl/pull/3577, https://github.com/JuliaPlots/Plots.jl/issues/3921.

Ran `Plots.jl` test suite without any apparent issue.

### CODE REVIEW

**Comment by t-bltg** [comment]
@BeastyBlacksmith, can you disable the `AppVeyor` CI action ? I don't think we'll use it anymore, and I don't have access to the settings of any `JuliaPlots` organization repo.

**Review by BeastyBlacksmith — APPROVED** [review]
In general I feel like this algorithm could try harder to show more than two ticks on log scales, but overall this is already an imrpovement

**Comment by ffreyer** [comment]
Looks like this messed up Makie's ticks in some cases. 

With v1.0.15:
```julia
ticks = PlotUtils.optimize_ticks(0.25314125f0, 0.94421935f0, k_min = 4, k_max = 8)[1]
# [0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9]
Showoff.showoff(ticks, :plain)
# ["0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9"]
```

With v1.1.0:
```julia
ticks = PlotUtils.optimize_ticks(0.25314125f0, 0.94421935f0, k_min = 4, k_max = 8)[1]
# Float32[0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.90000004]
Showoff.showoff(ticks, :plain)
# ["0.30000001", "0.40000001", "0.50000000", "0.60000002", "0.69999999", "0.80000001", "0.90000004"]
```

**Comment by t-bltg** [comment]
Ha, thanks for reporting, will fix.

**Comment by ffreyer** [comment]
I'd expect that too. Maybe this should be fixed in Showoff or Makie?

**Comment by t-bltg** [comment]
> I'd expect that too. Maybe this should be fixed in Showoff or Makie?

I'm not familiar with `Showoff`, but the easiest would be to cast to the correct type in `Makie`:
```bash
$ grep -r optimize_ticks
src/basic_recipes/axis.jl:    scaled_ticks, mini, maxi = optimize_ticks(
src/basic_recipes/axis.jl:    scaled_ticks, mini, maxi = optimize_ticks(
src/makielayout/ticklocators/wilkinson.jl:    tickvalues, _ = PlotUtils.optimize_ticks(vmin, vmax;
```
, only 3 occurrences in `Makie`.

**Comment by t-bltg** [comment]
Seems like I introduced type instability in this PR, fix is underway ...

**Pull request merged**
