### PR TITLE
Use StableRNGs for `adapted_grid()`

### PR DESCRIPTION
**Pull request by ffreyer**
Julia 1.11 changed something about random number generation which causes `rand(MersenneTwister(1337))` to return a different result from <1.11. This results in a different point selection in `adapted_grid` and causes a test failure in Makie. Making `rng` a kwarg doesn't fix the difference between versions, but allows for other packages to use StableRNG if they care about consistency

### CODE REVIEW

**Review by asinghvi17 — COMMENTED** [review]
Looks good to me, thanks!

**Comment by ffreyer** [comment]
I'm not sure about this yet. The master version always reset the RNG so the results are always consistent for same inputs. This may or may not, depending on how it's used. E.g. if you set `const RNG = Xoshiro(123)` and pass that, you will advance the rng between calls and not get the same output. Re-seeding the rng is dodgy, since it could also be `Random.default_rng()`.

I wonder if this could use a weaker factor instead, or if we should just make this a StableRNG in general.

**Comment by BeastyBlacksmith** [comment]
> we should just make this a StableRNG in general.

I'd say we do this, since we just need some random numbers. Possibly making the rand_factor a callsite argument, since people might be more interested to tweak that instead of the RN stream.

**Comment by jkrumbiegel** [comment]
> we should just make this a StableRNG in general.

Sounds good to me, and if you really want to give people the ability to try different seeds then you could also just make the seed itself a kwarg and then do `rng = StableRNG(seed)` in the function. But for me it would also be fine without that.

**Comment by jkrumbiegel** [comment]
Another idea, it seems to me that we could also get by using `sin` as the "random number generator" as we will never get the same numbers twice out of it when passing integers (as no natural number is divisible by pi). Previously the random numbers were rescaled to -1, 1 and you get that automatically with `sin`. To make it more "random" one could also do `sin(1000 * i)` or so.

```diff
for i ∈ 2:(length(xs) - 1)
-        xs[i] += 2rand_factor * (rand(rng) - 0.5) * (xs[i + 1] - xs[i - 1])
+        xs[i] += rand_factor * sin(i) * (xs[i + 1] - xs[i - 1])
```

**Comment by ffreyer** [comment]
This fails:
```julia
let f = sinc, int = (0, 40)  # JuliaPlots/Plots.jl/issues/3894
    xs, fs = adapted_grid(f, int)
    @test length(xs) > 400
end
```

but it doesn't reproduce the problem from the issue. With `lines(-40..40, sinc)` in Makie:

grafik
grafik

The 0..40 range also looks good.

**Review by BeastyBlacksmith — APPROVED** [review]

**Pull request merged**
