### PR TITLE
Make misc color library a global const to reduce package load time.

### LINKED ISSUE #51: Reduce PlotUtils load time
PlotUtils contributes a significant chunk to the load time of Plots (see JuliaPlots/Plots.jl#1825).

Measuring the load time of PlotUtils via

    for i in 1 2 3 4 5; do julia -e '@time import PlotUtils'; done

I get:

*  PlotUtils: 1.5 s

Successively removing includes results in these load times:

* No "colors.jl", "adapted_grid.jl" and "gradients/*.jl": 1.5 s
* No "color_gradients.jl" : 0.7 s
* Empty PlotUtils (no code, only deps): 0.67 s

So the culprit seems to be "color_gradients.jl" itself (without the gradient files it includes).

### PR DESCRIPTION
**Pull request by oschulz**
Reduces load time of PlotUtils by 45% and total load time of Plots by 20%.

@SimonDanisch, you touched `__init__` last, is this Ok?

Closes #51.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Well, this segfaults with static compilation ;) Maybe there is another way to have this serialized at precompilation time & not segfault for static compilation. The problem is likely the dict, maybe a rehash is enough to fix it!

**Comment by oschulz** [comment]
Ah - I wasn't aware that we could use static compilation with Plots, yet. Or is it Makie?

**Comment by oschulz** [comment]
If serialization doesn't work, maybe we can load this in a lazy fashion when the color scales are used?

**Comment by oschulz** [comment]
> They are used always.

Surely we don't always use all of them?

**Comment by mkborregaard** [comment]
no - read the rest of my comment :-)

**Comment by oschulz** [comment]
Ok, can you take another look, @SimonDanisch? I use a global array now, it's a bit slower this way, but still a lot faster than the old `__init__()`.

**Comment by JeffBezanson** [comment]
Since the keys are symbols, this could use an `IdDict` and I believe everything should work.

**Comment by oschulz** [comment]
Switched to an `IdDict`, as suggested by @JeffBezanson.

**Comment by mkborregaard** [comment]
Great!

**Comment by JeffBezanson** [comment]
Sorry, I kind of didn't know what I was talking about here. I see that `ColorLibrary` has `::Dict` fields, so on construction the IdDicts will just be converted to Dicts, so that change has no effect.

**Comment by mkborregaard** [comment]
OK – @SimonDanisch do we need to revert this then? Don't want to break PackageCompiler!

**Comment by oschulz** [comment]
@JeffBezanson, would it be enough to change the `::Dict` fields in `ColorLibrary` to `IdDict`s as well?

**Pull request merged**
