### PR TITLE
Rework misc and add cividis

### PR DESCRIPTION
**Pull request by asinghvi17**
This PR spins the misc colour library off into its own file under `src/gradients`, and adds the `cividis` color map to it.  This color map is from https://arxiv.org/ftp/arxiv/papers/1712/1712.01662.pdf, and is an adaptation of the `viridis` colour map for people with colour vision deficiency.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Have you tested this with Plots and PlotThemes? PlotThemes uses the misc library to store gradients.

**Comment by asinghvi17** [comment]
Seems to work minimally with Plots and PlotThemes - simple line plots are fine.  I will run the full suite when my computer's plugged in - which it unfortunately isn't right now.  Thanks for the info, though!
Screen Shot 2019-04-22 at 5 15 09  26300PM
Screen Shot 2019-04-22 at 5 15 21  22600PM

**Comment by asinghvi17** [comment]
PlotThemes tests pass, but I'm not sure how comprehensive the test suite is.

**Comment by asinghvi17** [comment]
```julia
(v1.1) pkg> test PlotThemes
   Testing PlotThemes
    Status `/var/folders/gl/tdt9v5vj4xqg5cdsz0ll1j7h0000gn/T/tmpppbwM4/Manifest.toml`
  [...]
   Testing PlotThemes tests passed

(v1.1) pkg> test Plots
   Testing Plots
[...]
  Updating `/private/var/folders/gl/tdt9v5vj4xqg5cdsz0ll1j7h0000gn/T/tmp0e9axF/Project.toml`
  [c5e800db] + PlotReferenceImages v0.0.0 #master (https://github.com/JuliaPlots/PlotReferenceImages.jl.git)
  [995b91a9] ~ PlotUtils v0.5.8+ #as/cividis (https://github.com/JuliaPlots/PlotUtils.jl.git) ⇒ v0.5.8+ #master (https://github.com/JuliaPlots/PlotUtils.jl.git)
  [3cdcf5f2] ↑ RecipesBase v0.6.0 ⇒ v0.6.0+ #master (https://github.com/JuliaPlots/RecipesBase.jl.git)
  Updating `/private/var/folders/gl/tdt9v5vj4xqg5cdsz0ll1j7h0000gn/T/tmp0e9axF/Manifest.toml`
  [c5e800db] + PlotReferenceImages v0.0.0 #master (https://github.com/JuliaPlots/PlotReferenceImages.jl.git)
  [995b91a9] ~ PlotUtils v0.5.8+ #as/cividis (https://github.com/JuliaPlots/PlotUtils.jl.git) ⇒ v0.5.8+ #master (https://github.com/JuliaPlots/PlotUtils.jl.git)
  [3cdcf5f2] ↑ RecipesBase v0.6.0 ⇒ v0.6.0+ #master (https://github.com/JuliaPlots/RecipesBase.jl.git)
  Building Conda ──────→ `~/.julia/packages/Conda/CpuvI/deps/build.log`
 Resolving package versions...
  Building FFTW ───────→ `~/.julia/packages/FFTW/p7sLQ/deps/build.log`
 Resolving package versions...
  Building ImageMagick → `~/.julia/packages/ImageMagick/d5KBL/deps/build.log`
 Resolving package versions...
Test Summary: | Pass  Total
GR            |    2      2
 [...]
Test Summary: | Pass  Total
UnicodePlots  |    6      6
Test Summary: | Pass  Total
Axes          |    6      6
Test Summary: |
NoFail        | No tests
   Testing Plots tests passed

**Comment by asinghvi17** [comment]
Tests seem to pass on Plots and PlotThemes.

**Comment by mkborregaard** [comment]
Great! Yeah PlotThemes' tests are a joke, but it looks like this works :-)

**Pull request merged**
