### PR TITLE
RFC: favor tightest ticks

### PR DESCRIPTION
**Pull request by piever**
This PR makes sure that, should an exact solution with `strict_span = true` not exist, the tightest fit is selected.

3 Example plots:

```julia
scatter(rand(100), rand(100))
plot(sin, -pi, pi)
density(linspace(0.2291313228541989, 0.3318750511155737, 100))
```

Master:
randold
sineold
densityold

PR:
rand
sine
density

See Plots issue [#1045](https://github.com/JuliaPlots/Plots.jl/issues/1045)

### CODE REVIEW

**Comment by piever** [comment]
Copy pasted gitter for context:

> Daniel Schwabeneder @daschw 18:11
> why do you think the strict_span option is broken?
> 
> piever @piever 18:16
> https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/ticks.jl#L97
> here it only allows ticks if the span is larger than xspan
> (which is the span of the data)
> and here it punishes it with a constant cost
> https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/ticks.jl#L125
> which is always given, because the condition is always true, so it's ineffective
> one could put a cost like: 10000(span/xspan + 1) so that of the options with span>xspan, it would choose the smallest
> let's be more precise, it's broken when no exact solution from xmin to xmax exists
> 
> Daniel Schwabeneder @daschw 18:24
> but that just means that an exact solution gets a significantly higher score than all the others and will be chosen (if it exists), right?
> 
> piever @piever 18:26
> yes, but it also means that when no exact solutions exist (see for example the issue on Plots) there is no penalty for going out of the margin a lot
> for example if you try it on optimize_ticks(2.29,3.3; k_min = 5, k_max = 8)
> its preferred solution is [0, 1, 2, 3, 4 ] which then gets filtered down to [3]
> 
> Daniel Schwabeneder @daschw 18:28
> I see
> 
> piever @piever 18:29
> a simple fix is to have this cost instead 10000(span/xspan + 1) so that of all the options that are outside, it takes the tightest one
> but I'm not sure that's ideal, I'll open a PR on PlotUtils so we can discuss there
> 
> Daniel Schwabeneder @daschw 18:30
> I guess you could try your suggestion above in a PR and see how it works for different examples.
>

**Comment by mkborregaard** [comment]
Can you post the plot calls too? And which of the plots are with master, which with this PR?

**Comment by daschw** [comment]
I'm not so sure about the last image. Wouldn't "rounder" `xtick` positions like `[0.2, 0.25, 0.3, 0.35]` be nicer?
Another option would be to replace `4.0` with a lower value like `2.0` here: https://github.com/JuliaPlots/PlotUtils.jl/pull/26/files#diff-e5f2a03bcdb4bfecfe02cefba18a39bdL127. This would keep the scoring algorithm as it is and limit the number of allowed results with respect to span.
See also the discussion in https://github.com/JuliaPlots/PlotUtils.jl/pull/11

**Comment by piever** [comment]
> Can you post the plot calls too? And which of the plots are with master, which with this PR?Agreed! 

I've just updated the first post.

> I'm not so sure about the last image. Wouldn't "rounder" xtick positions like [0.2, 0.25, 0.3, 0.35] be nicer?
> Another option would be to replace 4.0 with a lower value like 2.0 here:

It's true that my solution goes for the tightest fit but then neglects the other criteria, your approach would probably be better, I can check (quick question: is there an easy way to change this file and do the plot with the updated version without to much recompiling? Otherwise it's a bit of a struggle to fine tune parameters).

Another thing worth noting is that sometimes too many ticks get cropped. We should maybe, in case of strict span, consider as `k_min`, `k_ideal` and `k_max` the number of ticks after cropping. In that way we could keep using `strict_span = true` when the number of ticks is given as an integer.

**Comment by piever** [comment]
Same plot with @daschw idea (scatter plot depends on exactly which points get sampled):

scatter2
scatter
sin

density

**Comment by piever** [comment]
One thing to decide is whether we want to allow the ticks to determine the size of the axis. If we don't, I think there will alway be the possibility of getting something a bit strange like `[0.2, 0.4, 0.6, 0.8, 1]` because `0.0` is considered out of range. On the other hand, it seems like allowing the ticks to determine the axis size could be dangerous.

**Comment by mkborregaard** [comment]
They do decide that to a certain degree already, no?

**Comment by piever** [comment]
I see, that's the part I was missing. Then @daschw idea is probably the best way to go. The only improvement would be if we want to force `k_min` etc. to actually act on the ticks that will be selected after trimming (otherwise, the only difference between `strict_span = true` or `false` is that one trims and the other doesn't, with the unpleasant consequence that the one which does trim may not respect the conditions on the number of ticks)

**Comment by mkborregaard** [comment]
I don't know the ticks code very well, @daschw is much more into that. But here are some thoughts:

1. I think there are too few tickmarks on many of those plots. The rule of thumb is 5-8, IMHO 4 is also good.
2. I think the most important factor is human-readability, so the second version of the density function is a big improvement on the first.
3. I think the ticks should naturally play a role in setting the lims, but possibly not too far. I.e. I find nothing wrong with `[0.2, 0.4, 0.6, 0.8, 1]`.
(4. On a side note, we need to also call adapted_grid on a function even when x and y limits are passed).

**Comment by piever** [comment]
I agree on all of those points. The best would then seem @daschw idea plus one of the following two options:

- make sure that `k_min`, `k_max` and `k_ideal` refer to the effective number of ticks so that `k_min = 5` is actually respected
- increase `k_min`, `k_max` and `k_ideal` default values.

The first seems more principled, I can give it a go when I have a bit more time (it could be a bit tricky to implement).

**Comment by daschw** [comment]
I think the easier option would be the second one, hard to say ...

Here's the result of
```julia
histogram([length(PlotUtils.optimize_ticks(extrema(rand(2))... ,
    strict_span = true, k_min = 5, k_max = 8)[1]) for i in 1:100000],
    xguide = "Number of ticks", yguide = "Frequency",
    title = "Number of ticks returned by optimize_ticks", label = "")
```
on master:
number_of_ticks
There seem to be quite a lot degenerate cases with only 1 or 2 ticks.
@piever maybe you could compare this to the result after this PR and different values for `k_min` and `kmax`?

**Comment by piever** [comment]
Interesting analysis!

> I think the easier option would be the second one, hard to say ...

I actually think the level of variability you get suggests that option 1 would work better. Also, it would resolve the problem that now when the exact number of ticks is given, we need to turn `strict_span` off, which can give visually unpleasant results.

**Comment by daschw** [comment]
I'm all for the first option, if you find a nice solution!

**Comment by piever** [comment]
I think it's just about shuffling the code: like this it should work, I'll what the above plots and the histogram look like.

**Comment by piever** [comment]
Histogram from 4 to 8:

hist

**Comment by piever** [comment]
And here are the usual plots, where I moved Plots criterion for the number of ticks from 5,8 to 4,8 (so that a solution always exists):

rand
sin
density

**Comment by mkborregaard** [comment]
This looks great 👍

**Comment by daschw** [comment]
Great @piever! Really nice work!
I'm for the minimum 4 ticks option, but could imagine maximally 9. (I think I would even allow just 3 ticks, but I'm not sure about this.)
Are you both favouring at least 5 ticks?

**Comment by piever** [comment]
After playing a bit more with it, I actually also prefer 4 to 8 (especially when doing plots with several subplots: it gets crowded really quickly). In the future, I can also imagine allowing `xticks = (a, b)`, which would call `optimize_ticks(...; k_min = a, k_max = b)`, so that users could set their own preference in `PLOTS_DEFAULTS`.

**Comment by mkborregaard** [comment]
> After playing a bit more with it, I actually also prefer 4 to 8
👍 

Not so much the xticks idea. But otherwise, really cool stuff!

**Comment by mkborregaard** [comment]
Possibly as a result of this - it seems as if the axis limits aren't counted as ticks, which I think they should be if there are 4-8 ticks, and also that makes the plot easier to read. Here's an example:
```
plot([sin, cos], 0, 20, ribbon = 0.5) 
```
skaermbillede 2017-10-03 kl 22 34 51
I'd expect the ticks to be at 0, 5, 10, 15 and 20.

**Comment by piever** [comment]
I completely agree and indeed:

```julia
julia> x = 0:0.1:20
0.0:0.1:20.0

julia> plot(x, sin.(x))
```

gives the correct ticks (0:5:20). I think that the issue is not with the tick algorithm which I believe now works correctly, but with the computation of the axis limits (ticks are programmed to be within axis limits). I haven't looked carefully into the example, but what I believe is happening is that 0 and 20 are outside of the axis limits, so that solution is not considered acceptable. I'm not too sure where/how axis limits are being computed though.

**Comment by piever** [comment]
Even `plot([sin, cos], 0, 20, ribbon = 0.5, xlims = (0,20))` gives the correct ticks, it definitely is a problem with computing the extrema of the x axis.

**Comment by mkborregaard** [comment]
We should probably open an issue

**Pull request merged**
