### PR TITLE
fixes for julia 0.7

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Are these changes relevant for 0.6 as well? Otherwise, could you make this against the 0.7 branch instead. Master still tracks 0.7 in JuliaPlots - @daschw when do you think will be the right time to make the switch - once femtocleaner comes fully online?

We could base a release of this off the 0.7 branch already.

**Comment by mkborregaard** [comment]
The Travis error seems unrelated

**Comment by fredrikekre** [comment]
Whats the reason for the 0.7 branch?

**Comment by daschw** [comment]
I'm not sure. Did we have a 0.6 branch for the last switch @mkborregaard ?

**Comment by fredrikekre** [comment]
I included two of the commits from the `julia0.7`. 0a044159df954ba29f61ae21d1f6c97255842350 is wrong, it will install the old Dates package that is for Julia 0.3 and not the one that is currently in stdlib, so I excluded that.

**Comment by fredrikekre** [comment]
bump

**Comment by mkborregaard** [comment]
I am currently on my phone in Tanzania and will have extending limited email access until the beginning of August. I hope someone else can handle this, sorry. 
________________________________________

**Comment by fredrikekre** [comment]
> Is there any reason not to just merge this into master?

No, not in my opinion. There has not been any functional changes since almost a year, and there is not reason to believe there is need for another julia v0.6 release. It would help upgrading other dependent packages if this could be merged and released.

**Comment by daschw** [comment]
Thanks!

**Pull request merged**
